spring:
  cloud:
    stream:
      bindings:
        input:
          destination: stream-control-notifications
          binder: local_rabbit
#          group: recommendations --asi es como se define un consumer group
#        output:
#          destination: stream-control-notifications
#          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: <username>
                password: <password>
                virtual-host: /