global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'dynamic-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['100.109.0.2:9080'] #Provide your ip and Do not give localhost as we are running the prometheus in docker
      labels:
        application: dynamic-service
